controller
diegoTorrezG/minga-backend pull request #2
Opened 2023-01-03 15:03 UTC by LuRovere

2023-01-03 15:05 UTC, Gustasco approved these changes

2023-01-03 17:26 UTC, ignacioborraz commented on bin/www.js
> +import debug from'debug';//
este pequeño cambio que seria? no deberias tocar los archivos "generales" de la app con tu tarea

2023-01-03 17:27 UTC, ignacioborraz commented on config/database.js
> -import mongoose from 'mongoose'
esta configuracion es la vieja! volve a pushear la nueva

2023-01-03 19:13 UTC, camilo-sanchez-2810 commented on models/Chapter.js
> +    comic_id:{type:Object, required:true},
El tipo de dato de comic_id es mongoose.Types.ObjectId, no Object

2023-01-03 19:15 UTC, camilo-sanchez-2810 requested changes
Cambia el tipo de dato de comic_id

2023-01-03 19:25 UTC, camilo-sanchez-2810 commented on models/Chapter.js
> +    comic_id:{type:Object, required:true},
Tambien te falto agregar la referencia a comics

2023-01-03 21:30 UTC, camilo-sanchez-2810 reviewed
Si

2023-01-04 13:39 UTC, LuRovere commented on schemas/chapter.schema.js
> +    pages: Joi.array().required(),
agregar validacion para que cada elemento del array sea una url
utilizar el metodo uri()

2023-01-05 15:11 UTC, merged